name: Generate docs from pod

on:
  push:
    branches:
      - main

jobs:
  get-token:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions: {}
    outputs:
      token: ${{ steps.app-token.outputs.token }}
    steps:
      - uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        id: app-token
        with:
          app-id: ${{ secrets.PODENO_APP_ID }}
          private-key: ${{ secrets.PODENO_PRIVATE_KEY }}
          permission-contents: write
          permission-pull-requests: write
  generate-doc:
    needs: get-token
    uses: Omochice/tataku-share-actions/.github/workflows/generate-doc.yml@afbf9f2ac6464bc14aa7ac28e14e2b92e800dd3a # v1.0.3
    permissions:
      contents: write
      pull-requests: write
    secrets:
      token: ${{ needs.get-token.outputs.token }}
